<!DOCTYPE html>
<html>
<head>
    <title>PHP Test</title>
</head>
<body>
    <h1>Welcome to PHP!</h1>
    <?php
        // echo "This is generated by PHP.";
       $john = $test = $name = "John Doe";
        echo $john;
        echo $test;
        echo $name;
    ?>
</body>
</html>
